name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
runs:
  using: composite
  steps:
    - name: Run container with DB
      shell: bash
      run: docker build . --file ./src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)
    
    - name: List containers
      shell: bash
      run: docker ps

