name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile-path:
    description: "Path to the Dockerfile"
    type: string
    required: false
  image-tag:
    description: "Tag to the image"
    type: string
    required: false
    
runs:
  using: composite
  steps:
  
    - name: Run container with DB
      shell: bash
      run: docker build . --file '$DOCKERFILE_PATH' --tag academy:'$IMAGE_TAG'
    
    - name: List containers
      shell: bash
      run: docker images

