name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      dockerfile-path:
        description: 'Path to the dockerfile'
        required: false
        type: string
      image-tag:
        description: 'Tag to the docker image'
        required: false
        type: string

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: AntonioF01/academy-ctw/.github/actions/maven_build@main
    - uses: AntonioF01/academy-ctw/.github/actions/docker_build@main
      with:
        dockerfile-path: "./src/main/docker/Dockerfile.jvm"
        image-tag: "$(date +%s)"
    
